workflows:
  run-testsigma:
    name: Run Testsigma Shell Script
    scripts:
      - name: Trigger Testsigma
        script: |
          chmod +x ./magictrigger.sh
          ./magictrigger.sh

    artifacts:
      - junit-report-testplan-*.xml
      - testsigma-response-testplan-*.json
